server_url: https://headscale.tailnet.work
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090
grpc_listen_addr: 0.0.0.0:50443

database:
  type: postgres
  postgres:
    host: headscale_postgres
    port: 5432
    name: headscale
    user: headscale
    pass: headscale_password

private_key_path: /var/lib/headscale/private.key
noise:
  private_key_path: /var/lib/headscale/noise_private.key

prefixes:
  v4: 100.64.0.0/16
  v6: fd7a:115c:a1e0::/48

derp:
  server:
    enabled: false
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  paths: []
  auto_update_enabled: true
  update_frequency: 24h

dns:
  override_local_dns: true
  nameservers:
    global:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9
  search_domains: ["company.internal"]
  magic_dns: true
  base_domain: company.internal

oidc:
  only_start_if_oidc_is_available: false

policy:
  mode: database

log:
  format: json
  level: info

unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"

disable_check_updates: true
randomize_client_port: false
machine_registration_timeout: "10m"
node_update_check_interval: "10s"
enable_metrics: true
ephemeral_node_inactivity_timeout: "30m"

websocket:
  enabled: true
