http:
  host: '0.0.0.0'
  port: 3000
  public_url: "https://admin.tailnet.work"

user_storage_file: "/var/lib/headplane/users.json"

headscale:
  url: "http://headscale:8080"
  config_path: "/etc/headscale/config.yaml"
  dns_records_path: "/etc/headscale/dns_records.json"
  config_strict: true

integration:
  docker:
    enabled: true
    container_label:
      name: "com.headplane.selector"
      value: "headscale"
    socket: "unix:///var/run/docker.sock"
  
  kubernetes:
    enabled: false
    
  proc:
    enabled: false

oidc:
  issuer: "https://auth.tailnet.work"
  client_id: "headscale-ui-client"
  client_secret: "${HEADPLANE_OIDC_SECRET}"
  disable_api_key_login: false
  token_endpoint_auth_method: "client_secret_post"
  headscale_api_key: "${HEADSCALE_ROOT_API_KEY}"
  redirect_uri: "https://admin.tailnet.work/admin/oidc/callback"
  scopes: ["openid", "profile", "email", "groups"]
  claims_mapping:
    username: "preferred_username"
    email: "email"
    groups: "groups"
    display_name: "name"

logging:
  level: "info"
  format: "json"

session:
  cookie_name: "headplane_session"
  max_age: 28800
  secure: true
  http_only: true
  same_site: "lax"

security:
  allowed_origins:
    - "https://admin.tailnet.work"
    - "https://auth.tailnet.work"
  trusted_proxies:
    - "172.16.0.0/12"
    - "192.168.0.0/16"
    - "10.0.0.0/8"
