networks:
  headscale_internal:
    external: true
  proxy:
    external: true

volumes:
  headplane_data:
    driver: local

services:
  headplane:
    image: ghcr.io/tale/headplane:0.6.0
    container_name: headplane
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - HEADPLANE_DEBUG_LOG=false
      - HEADPLANE_LOAD_ENV_OVERRIDES=true
      - HEADPLANE_OIDC__ISSUER=https://auth.tailnet.work
      - HEADPLANE_OIDC__CLIENT_ID=headscale-ui-client
      - HEADPLANE_OIDC__CLIENT_SECRET=${HEADPLANE_OIDC_SECRET}
      - HEADPLANE_OIDC__HEADSCALE_API_KEY=${HEADSCALE_ROOT_API_KEY}
      - HEADPLANE_OIDC__DISABLE_API_KEY_LOGIN=false
      - HEADPLANE_OIDC__REDIRECT_URI=https://admin.tailnet.work/admin/oidc/callback
    volumes:
      - ./config/config.yaml:/etc/headplane/config.yaml:ro
      - ../headscale/config/config.yaml:/etc/headscale/config.yaml:ro
      - ../headscale/config/dns_records.json:/etc/headscale/dns_records.json
      - headplane_data:/var/lib/headplane
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
      - headscale_internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.headplane.rule=Host(`admin.tailnet.work`)"
      - "traefik.http.routers.headplane.entrypoints=websecure"
      - "traefik.http.routers.headplane.tls=true"
      - "traefik.http.routers.headplane.tls.certresolver=letsencrypt"
      - "traefik.http.services.headplane.loadbalancer.server.port=3000"
      - "traefik.http.routers.headplane.middlewares=secure-headers"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
