global:
  smtp_smarthost: '${SMTP_HOST}:${SMTP_PORT}'
  smtp_from: '${SMTP_USERNAME}'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'email-critical'
  - match:
      severity: warning
    receiver: 'email-warning'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

- name: 'email-critical'
  email_configs:
  - to: 'admin@tailnet.work'
    headers:
      Subject: '[CRITICAL] Headscale Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

- name: 'email-warning'
  email_configs:
  - to: 'admin@tailnet.work'
    headers:
      Subject: '[WARNING] Headscale Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
