networks:
  proxy:
    external: true

volumes:
  letsencrypt:
    driver: local
  traefik_logs:
    driver: local

services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - letsencrypt:/letsencrypt
      - traefik_logs:/var/log
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.tailnet.work`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=admin-auth,secure-headers"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "--no-check-certificate", "https://localhost:443/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
