global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  debug: false
  insecure: false

log:
  level: INFO
  format: json
  filePath: "/var/log/traefik.log"

accessLog:
  format: json
  filePath: "/var/log/access.log"
  bufferingSize: 100

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        options: default

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
    watch: true
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      tlsChallenge: {}
      email: admin@tailnet.work
      storage: /letsencrypt/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true

ping:
  entryPoint: "websecure"

serversTransport:
  insecureSkipVerify: true
